name: Revert and Create PR

on:
  push:
    branches:
      - main

jobs:
  revert_and_create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "Push controller"
        git config --global user.email "action@github.com"

    - name: Reset to the last remote commit
      run: |
        git fetch origin
        git reset --hard origin/main

    - name: Stash changes if any
      run: |
        git stash || echo "No changes to stash"   


    - name: Create a new branch with the pushed changes
      run: |
        git checkout -b revert-branch
        git add .
        git commit -m "Reapply changes after revert to remote state"
        git push origin revert-branch

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
        head: revert-branch
        title: "Reapply changes after reverting to the latest remote commit"
        body: "This PR contains the changes after reverting the main branch to the state of the latest remote commit."        